### ISSUE TITLE
Private Repositoryの草を取得

### ISSUE THREAD

**Issue by ktanaka117** [Yu-taro/taue#12]

**Comment by yutailang0119** [comment]
Hi @ktanaka117 

Taue can already collect activities on GitHub and GitLab private repositories.
https://github.com/Yu-taro/taue/blob/develop/README.md

### GitHub
Please get your [private access token](https://github.com/settings/tokens) and check `repo:status`.
Add this token  to `githubToken` on Users.json.

### GitLab
GitLab API is a little unique.
First please get your [private token](https://gitlab.com/profile/personal_access_tokens).
* `Expires at`: token expired date. If it blank is indefinitely.
* `Scopes`: check `api Access your API` 
Second call this API (https://gitlab.com/api/v3/projects?private_token=xxxxxxxxxxxxx) with token.
```javascript
[
    {
    ...
        "owner": {
            "name": "",
            "username": "",
            "id": 123456,
            "state": "active",
            "avatar_url": "",
            "web_url": ""
        }
    ...
    },
    { ... }
]
```
This id is `gitlabId`.
Finally add this id and token to `gitlabId`, `gitlabToken` on Users.json.

If the problem is not resolved, please reopen this issue.
Thanks!

**Comment by cm-TanakaKenji** [comment]
@Yu-taro Thank you for your politeness.
